services:
  app:
    image: "${DOCKERHUB_USERNAME}/laptop-gg:latest"
    ports:
      - "8080:8080"
    environment:
      - PROFILE=deploy
    volumes:
      - /home/iggyu/data/LaptopGG.sqlite:/LaptopGG/LaptopGG.sqlite

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로 마운트

