services:
  app:
    image: "${DOCKERHUB_USERNAME}/laptop-gg:latest"
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - PROFILE=deploy
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=Asia/Seoul
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /home/iggyu/mariaDB/data/:/var/lib/mysql
      - /home/iggyu/mariaDB/conf/custom.cnf:/etc/mysql/mariadb.conf.d/custom.cnf
      - /home/iggyu/mariaDB/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
#    options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
