services:
  app:
    image: "${DOCKERHUB_USERNAME}/laptop-gg:latest"
    ports:
      - "8080:8080"
    environment:
      - PROFILE=deploy
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /home/iggyu/mariaDB/data/:/var/lib/mysql
      - /home/iggyu/mariaDB/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - /home/iggyu/mariaDB/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
