services:
  app:
    image: "${DOCKERHUB_USERNAME}/laptop-gg:latest"
    ports:
      - "8080:8080"
    environment:
      - PROFILE=deploy
    volumes:
      - /home/iggyu/data/LaptopGG.sqlite:/LaptopGG/LaptopGG.sqlite

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
