#spring:
#    datasource:
#        url: jdbc:sqlite:./LaptopGG.sqlite
#        driver-class-name: org.sqlite.JDBC
#        username: ""
#        password: ""
#
#    batch:
#        jdbc:
#            initialize-schema: always
#
#        job:
#            enabled: false
#
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#            hibernate:
#                dialect: org.hibernate.community.dialect.SQLiteDialect
#                format_sql: true
#                highlight_sql: true
#                use_sql_comments: true
#        show-sql: false
#
#    logging:
#        level:
#            org.hibernate.SQL: OFF
#            org.hibernate.type.descriptor.sql.BasicBinder: OFF
#
#---
spring:
    config:
        activate:
            on-profile: deploy
    datasource:
        url: jdbc:mariadb://db:3306/laptopgg?useUnicode=true&characterEncoding=utf8mb4&character_set_server=utf8mb4&collation_server=utf8mb4_uca1400_ai_ci
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    batch:
        jdbc:
            initialize-schema: always

        job:
            enabled: false

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
        show-sql: false

    logging:
        level:
            org.hibernate.SQL: OFF
            org.hibernate.type.descriptor.sql.BasicBinder: OFF

    api:
        base-url: "https://laptopgg.com"
#---
#spring:
#    config:
#        activate:
#            on-profile: ubuntu
#    datasource:
#        url: jdbc:sqlite:/home/iggyu/data/LaptopGG.sqlite
#        driver-class-name: org.sqlite.JDBC
#        username: ""
#        password: ""
#
#    batch:
#        jdbc:
#            initialize-schema: always
#
#        job:
#            enabled: false
#
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#            hibernate:
#                dialect: org.hibernate.community.dialect.SQLiteDialect
#                format_sql: true
#                highlight_sql: true
#                use_sql_comments: true
#        show-sql: false
#
#    logging:
#        level:
#            org.hibernate.SQL: OFF
#            org.hibernate.type.descriptor.sql.BasicBinder: OFF
#
#    api:
#        base-url: "http://localhost:8080"
#
---
spring:
    config:
        activate:
            on-profile: windows
    datasource:
        url: jdbc:mariadb://localhost:3306/laptopgg?useUnicode=true&characterEncoding=utf8mb4&character_set_server=utf8mb4&collation_server=utf8mb4_uca1400_ai_ci
        driver-class-name: org.mariadb.jdbc.Driver
        username: "root"
        password: "0000"

    batch:
        jdbc:
            initialize-schema: always

        job:
            enabled: false

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
        show-sql: false

    logging:
        level:
            org.hibernate.SQL: OFF
            org.hibernate.type.descriptor.sql.BasicBinder: OFF
    api:
        base-url: "http://localhost:8080"

