spring:
    config:
        activate:
            on-profile: deploy
    datasource:
        url: jdbc:mariadb://db:3306/${MYSQL_DATABASE}
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    batch:
        jdbc:
            initialize-schema: always

        job:
            enabled: false

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
        show-sql: false

    logging:
        level:
            org.hibernate.SQL: OFF
            org.hibernate.type.descriptor.sql.BasicBinder: OFF

    api:
        base-url: "https://laptopgg.com"

    sql:
        init:
            mode: always

---
spring:
    config:
        activate:
            on-profile: windows
    datasource:
        url: jdbc:mariadb://localhost:3306/laptopgg
        driver-class-name: org.mariadb.jdbc.Driver
        username: "root"
        password: "0000"

    batch:
        jdbc:
            initialize-schema: always

        job:
            enabled: false

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
        show-sql: false

    logging:
        level:
            org.hibernate.SQL: OFF
            org.hibernate.type.descriptor.sql.BasicBinder: OFF
    api:
        base-url: "http://localhost:8080"

    sql:
        init:
            mode: always
            scripts:
                - classpath:schema.sql

