spring:
    datasource:
        url: jdbc:sqlite:memory:myDb?cache=shared
        driver-class-name: org.sqlite.JDBC
        username: ""
        password: ""
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect
