logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

app:
  api:
    base-url: "http://localhost:8080"
  crawler:
    run-on-startup: false
    limit: ${CRAWLER_LIMIT:}

spring:
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/laptopgg}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:laptopgg}
    password: ${SPRING_DATASOURCE_PASSWORD:laptopgg}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:6}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}

  sql:
    init:
      mode: always
      platform: postgresql

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false

app:
  api:
    base-url: ${APP_BASE_URL:http://localhost:8080}

---
spring:
  config:
    activate:
      on-profile: deploy

app:
  api:
    base-url: "https://laptopgg.com"

---
spring:
  config:
    activate:
      on-profile: crawler

  main:
    web-application-type: none

app:
  crawler:
    run-on-startup: true
