spring:
    datasource:
        url: jdbc:sqlite:./LaptopGG.sqlite
        driver-class-name: org.sqlite.JDBC
        username: ""
        password: ""
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect
                format_sql: true    # 쿼리를 보기 쉽게 포맷
        show-sql: true              # SQL 쿼리 로그 활성화
    logging:
        level:
            org.hibernate.SQL: DEBUG                     # SQL 쿼리 로그 출력
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 바인딩 로그 출력

---
spring:
    config:
        activate:
            on-profile: deploy
    datasource:
        url: jdbc:sqlite:/LaptopGG/LaptopGG.sqlite
        driver-class-name: org.sqlite.JDBC
        username: ""
        password: ""
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect
                format_sql: true
        show-sql: true
    logging:
        level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
    config:
        activate:
            on-profile: ubuntu
    datasource:
        url: jdbc:sqlite:/home/iggyu/data/LaptopGG.sqlite
        driver-class-name: org.sqlite.JDBC
        username: ""
        password: ""
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.SQLiteDialect
                format_sql: true
        show-sql: true
    logging:
        level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE
