package going9.laptopgg.application.crawler.persistence

import java.time.LocalDateTime

data class PersistedCrawledLaptopSnapshot(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val detailPage: String,
    val productCode: String?,
    val price: Int?,
    val cpuManufacturer: String?,
    val cpu: String?,
    val os: String?,
    val screenSize: Int?,
    val resolution: String?,
    val brightness: Int?,
    val refreshRate: Int?,
    val ramSize: Int?,
    val ramType: String?,
    val isRamReplaceable: Boolean?,
    val graphicsType: String?,
    val tgp: Int?,
    val thunderboltCount: Int?,
    val usbCCount: Int?,
    val usbACount: Int?,
    val sdCard: String?,
    val isSupportsPdCharging: Boolean?,
    val batteryCapacity: Double?,
    val storageCapacity: Int?,
    val storageSlotCount: Int?,
    val weight: Double?,
    val lastDetailedCrawledAt: LocalDateTime?,
    val usages: List<String>,
)

data class ExistingCrawledLaptopSnapshot(
    val id: Long,
    val productCode: String?,
    val detailPage: String,
    val cpuManufacturer: String?,
    val cpu: String?,
    val os: String?,
    val screenSize: Int?,
    val resolution: String?,
    val ramSize: Int?,
    val graphicsType: String?,
    val storageCapacity: Int?,
    val batteryCapacity: Double?,
    val weight: Double?,
    val lastDetailedCrawledAt: LocalDateTime?,
    val usageCount: Int,
)
