logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

app:
  security:
    password:
      bcrypt-strength: ${APP_SECURITY_PASSWORD_BCRYPT_STRENGTH:10}

spring:
  config:
    import: classpath:/laptopgg-persistence.yml

  sql:
    init:
      mode: never

server:
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:32}
      min-spare: ${SERVER_TOMCAT_THREADS_MIN_SPARE:4}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: deploy

  flyway:
    baseline-on-migrate: false
